{{ if (.Values.CONCEPT_CATALOGUE_GUI_IMAGE) and .Values.CONCEPT_CATALOGUE_GUI_IMAGE "true" }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: concept-catalogue-gui
  name: concept-catalogue-gui
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "3111"
    port: 3111
    targetPort: 3111
  selector:
    fdk.service: concept-catalogue-gui
status:
  loadBalancer: {}
{{ else }} {{ end }}