{{ if (.Values.CONCEPT_CATALOGUE_IMAGE) and .Values.CONCEPT_CATALOGUE_IMAGE "true" }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: concept-catalogue
  name: concept-catalogue
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: concept-catalogue
status:
  loadBalancer: {}
{{ else }} {{ end }}