apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: concept-client
  name: concept-client
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: concept-client
    spec:
      containers:
      - args:
        - npm
        - start
        env:
        - name: NODE_ENV
          value: {{ required "Missing value FDK_CONCEPT_CLIENT_NODE_ENV" .Values.FDK_CONCEPT_CLIENT_NODE_ENV }}
        image: {{ required "Missing value CONCEPT_CLIENT_IMAGE" .Values.CONCEPT_CLIENT_IMAGE }}
        imagePullPolicy: Always
        name: concept-client
        ports:
        - containerPort: 4300
        resources:
          requests:
            memory: {{  required "Missing value FDK_CONCEPT_CLIENT_MEMORY" .Values.FDK_CONCEPT_CLIENT_MEMORY | quote }}
      restartPolicy: Always
status: {}
