{{ if (.Values.CONCEPT_CATALOGUE_IMAGE) and .Values.CONCEPT_CATALOGUE_IMAGE "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: concept-catalogue
  name: concept-catalogue
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: concept-catalogue
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ required "Missing value SPRING_PROFILES_ACTIVE" .Values.SPRING_PROFILES_ACTIVE }}
        - name: MONGO_USERNAME
          value: {{ required "Missing value FDK_CONCEPT_CATALOGUE_MONGO_USERNAME" .Values.FDK_CONCEPT_CATALOGUE_MONGO_USERNAME }}
        - name: MONGO_PASSWORD
          value: {{ required "Missing value FDK_CONCEPT_CATALOGUE_MONGO_PASSWORD" .Values.FDK_CONCEPT_CATALOGUE_MONGO_PASSWORD }}
        - name: RABBIT_USERNAME
          value: {{ required "Missing value FDK_RABBITMQ_DEFAULT_USER" .Values.FDK_RABBITMQ_DEFAULT_USER }}
        - name: RABBIT_PASSWORD
          value: {{ required "Missing value FDK_RABBITMQ_DEFAULT_PASS" .Values.FDK_RABBITMQ_DEFAULT_PASS }}
        - name: COLLECTION_BASE_URI
          value: {{ required "Missing value FDK_CONCEPT_CATALOGUE_COLLECTION_BASE_URI" .Values.FDK_CONCEPT_CATALOGUE_COLLECTION_BASE_URI }}
        image: {{ required "Missing value CONCEPT_CATALOGUE_IMAGE" .Values.CONCEPT_CATALOGUE_IMAGE }}
        imagePullPolicy: Always
        name: concept-catalogue
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value FDK_CONCEPT_CATALOGUE_MEMORY" .Values.FDK_CONCEPT_CATALOGUE_MEMORY | quote }}
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
      restartPolicy: Always
status: {}
{{ else }} {{ end }}
