apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: concept-catalogue-gui
  name: concept-catalogue-gui
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "4300"
    port: 4300
    targetPort: 4300
  selector:
    fdk.service: concept-catalogue-gui
status:
  loadBalancer: {}
