{{ if (.Values.CONCEPT_CATALOGUE_GUI_IMAGE) and .Values.CONCEPT_CATALOGUE_GUI_IMAGE "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: concept-catalogue-gui
  name: concept-catalogue-gui
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: concept-catalogue-gui
    spec:
      containers:
      - args:
        - npm
        - start
        env:
        - name: NODE_ENV
          value: {{ required "Missing value FDK_CONCEPT_CATALOGUE_GUI_NODE_ENV" .Values.FDK_CONCEPT_CATALOGUE_GUI_NODE_ENV }}
        - name: CONCEPT_REGISTRATION_API
          value: {{ required "Missing value FDK_CONCEPT_CATALOGUE_GUI_CONCEPT_REGISTRATION_API" .Values.FDK_CONCEPT_CATALOGUE_GUI_CONCEPT_REGISTRATION_API }}
        - name: PUBLISHER_API
          value: {{ required "Missing value FDK_CONCEPT_CATALOGUE_GUI_PUBLISHER_API" .Values.FDK_CONCEPT_CATALOGUE_GUI_PUBLISHER_API }}
        - name: PUBLISHER_DATA_AUTHORIZATION
          value: {{ .Values.FDK_CONCEPT_CATALOGUE_GUI_PUBLISHER_DATA_AUTHORIZATION }}
        - name: CONCEPT_API
          value: {{ .Values.FDK_CONCEPT_CATALOGUE_GUI_CONCEPT_API }}
        - name: REGISTRATION_HOST
          value: {{ .Values.FDK_CONCEPT_CATALOGUE_GUI_REGISTRATION_HOST }}
        image: {{ required "Missing value CONCEPT_CATALOGUE_GUI_IMAGE" .Values.CONCEPT_CATALOGUE_GUI_IMAGE }}
        imagePullPolicy: Always
        name: concept-catalogue-gui
        ports:
        - containerPort: 3111
        resources:
          requests:
            memory: {{  required "Missing value FDK_CONCEPT_CATALOGUE_GUI_MEMORY" .Values.FDK_CONCEPT_CATALOGUE_GUI_MEMORY | quote }}
      restartPolicy: Always
status: {}
{{ else }} {{ end }}
