{{ if (.Values.FDK_ADMIN_GUI_IMAGE) and .Values.FDK_ADMIN_GUI_IMAGE "true" }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-admin-gui
  name: fdk-admin-gui
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "8080"
    port: 8080
    targetPort: 8000
  selector:
    fdk.service: fdk-admin-gui
status:
  loadBalancer: {}
{{ else }} {{ end }}