{{ if (.Values.FDK_RABBITMQ_IMAGE) and .Values.FDK_RABBITMQ_IMAGE "true" }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-rabbitmq
  name: fdk-rabbitmq
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    fdk.service: fdk-rabbitmq
status:
  loadBalancer: {}
{{ else }} {{ end }}