{{ if (.Values.FDK_ADMIN_GUI_IMAGE) and .Values.FDK_ADMIN_GUI_IMAGE "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-admin-gui
  name: fdk-admin-gui
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: fdk-admin-gui
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: {{ required "Missing value FDK_CONCEPT_CATALOGUE_GUI_NODE_ENV" .Values.FDK_CONCEPT_CATALOGUE_GUI_NODE_ENV }}
        - name: CONCEPT_REGISTRATION_API
          value: {{ required "Missing value FDK_CONCEPT_CATALOGUE_GUI_CONCEPT_REGISTRATION_API" .Values.FDK_CONCEPT_CATALOGUE_GUI_CONCEPT_REGISTRATION_API }}
        image: {{ required "Missing value FDK_ADMIN_GUI_IMAGE" .Values.FDK_ADMIN_GUI_IMAGE }}
        imagePullPolicy: Always
        name: concept-catalogue-gui
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: {{  required "Missing value FDK_ADMIN_GUI_MEMORY" .Values.FDK_ADMIN_GUI_MEMORY | quote }}
      restartPolicy: Always
status: {}
{{ else }} {{ end }}
