{{ if (.Values.HARVESTER_API_IMAGE) and .Values.HARVESTER_API_IMAGE "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    fdk.service: harvester-api-claim0
  name: harvester-api-claim0
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
{{ else }} {{ end }}