{{ if (.Values.INFORMATIONMODEL_CAT_IMAGE) and .Values.INFORMATIONMODEL_CAT_IMAGE "true" }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: informationmodel-cat
  name: informationmodel-cat
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: informationmodel-cat
status:
  loadBalancer: {}
{{ else }} {{ end }}