{{ if (.Values.NGINX_ALTINN_PROXY_IMAGE) and .Values.NGINX_ALTINN_PROXY_IMAGE "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: nginx-altinn-proxy
  name: nginx-altinn-proxy
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: nginx-altinn-proxy
    spec:
      containers:
      - env:
        - name: ALTINN_HOST
          value: {{ required "Missing value FDK_NGINX_ALTINN_PROXY_ALTINN_HOST" .Values.FDK_NGINX_ALTINN_PROXY_ALTINN_HOST }}
        image: {{ required "Missing value NGINX_ALTINN_PROXY_IMAGE" .Values.NGINX_ALTINN_PROXY_IMAGE }}
        envFrom:
          -secretRef:
            name: fdk-altinnproxy-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}-brreg-altinn-key
        imagePullPolicy: Always
        name: nginx-altinn-proxy
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value FDK_NGINX_ALTINN_PROXY_MEMORY" .Values.FDK_NGINX_ALTINN_PROXY_MEMORY | quote }}
      restartPolicy: Always
status: {}
{{ else }} {{ end }}