{{ if (.Values.REFERENCE_DATA_IMAGE) and .Values.REFERENCE_DATA_IMAGE "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: reference-data
  name: reference-data
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: reference-data
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ required "Missing value SPRING_PROFILES_ACTIVE" .Values.SPRING_PROFILES_ACTIVE }}
        - name: themesHttpUsername
          value: {{ required "Missing value FDK_REFERENCE_DATA_THEMESHTTPUSERNAME" .Values.FDK_REFERENCE_DATA_THEMESHTTPUSERNAME }}
        - name: themesHttpPassword
          value: {{ required "Missing value FDK_REFERENCE_DATA_THEMESHTTPPASSWORD" .Values.FDK_REFERENCE_DATA_THEMESHTTPPASSWORD }}
        - name: FDK_SQL_JDBC_CONNECTION
          value: {{ required "Missing value FDK_REFERENCE_DATA_SQL_JDBC_CONNECTION" .Values.FDK_REFERENCE_DATA_SQL_JDBC_CONNECTION }}
        - name: FDK_SQL_USERNAME
          value: {{ required "Missing value FDK_REFERENCE_DATA_SQL_USERNAME" .Values.FDK_REFERENCE_DATA_SQL_USERNAME }}
        - name: FDK_SQL_PASSWORD
          value: {{ required "Missing value FDK_REFERENCE_DATA_SQL_PASSWORD" .Values.FDK_REFERENCE_DATA_SQL_PASSWORD }}
        image: {{ required "Missing value REFERENCE_DATA_IMAGE" .Values.REFERENCE_DATA_IMAGE }}
        imagePullPolicy: Always
        name: reference-data
        ports:
        - containerPort: 8080
        resources: 
          requests:
            memory: {{ required "Missing value FDK_REFERENCE_DATA_MEMORY" .Values.FDK_REFERENCE_DATA_MEMORY | quote }}
        volumeMounts:
        - mountPath: /tdb
          name: reference-data-claim0
      restartPolicy: Always
      volumes:
      - name: reference-data-claim0
        persistentVolumeClaim:
          claimName: reference-data-claim0
status: {}
{{ else }} {{ end }}