{{ if (.Values.SEARCH_IMAGE) and .Values.SEARCH_IMAGE "true" }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: search
  name: search
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: search
status:
  loadBalancer: {}
{{ else }} {{ end }}