{{ if (.Values.SEARCH_IMAGE) and .Values.SEARCH_IMAGE "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: search
  name: search
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: search
    spec:
      containers:
        - env:
          - name: CONTAINER_IMAGE
            value: {{ required "Missing value SEARCH_IMAGE" .Values.SEARCH_IMAGE }}
          - name: NODE_ENV
            value: {{ required "Missing value SEARCH_NODE_ENV" .Values.SEARCH_NODE_ENV }}
          - name: DISQUS_SHORTNAME
            value: {{ required "Missing value SEARCH_DISQUS_SHORTNAME" .Values.SEARCH_DISQUS_SHORTNAME }}
          - name: SEARCH_HOST
            value: {{ .Values.FDK_SEARCH_SEARCH_HOST }}
          - name: SEARCH_API_HOST
            value: {{ .Values.FDK_SEARCH_SEARCH_API_HOST }}
          - name: NAP_HOST
            value: {{ .Values.FDK_SEARCH_NAP_HOST }}
          - name: SEARCH_API_AUTHORIZATION
            value: {{ .Values.SEARCH_API_AUTHORIZATION }}
          - name: USE_DEMO_LOGO
            value: {{ .Values.USE_DEMO_LOGO | quote }}
          image: {{ required "Missing value SEARCH_IMAGE" .Values.SEARCH_IMAGE }}
          imagePullPolicy: Always
          name: search
          ports:
          - containerPort: 3000
          resources: 
            requests:
              memory: {{ required "Missing value FDK_SEARCH_MEMORY" .Values.FDK_SEARCH_MEMORY | quote }}
      restartPolicy: Always
status: {}
{{ else }} {{ end }}