{{ if (.Values.SSO_IMAGE) and .Values.SSO_IMAGE "true" }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    fdk.service: sso
  name: sso
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8084
  - name: "8080"
    port: 8080
    targetPort: 8084
  selector:
    fdk.service: sso
status:
  loadBalancer: {}
{{ else }} {{ end }}
