{{ if (.Values.USER_API_IMAGE) and .Values.USER_API_IMAGE "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: user-api
  name: user-api
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: user-api
    spec:
      containers:
      - env:
        - name: ALTINN_PROXY_HOST
          value: {{ required "Missing value FDK_USER_API_ALTINN_PROXY_HOST" .Values.FDK_USER_API_ALTINN_PROXY_HOST }}
        - name: ORGNR_WHITELIST
          value: {{ required "Missing value FDK_USER_API_ORGNR_WHITELIST" .Values.FDK_USER_API_ORGNR_WHITELIST | quote }}
        - name: ORGFORM_WHITELIST
          value: {{ required "Missing value FDK_USER_API_ORGFORM_WHITELIST" .Values.FDK_USER_API_ORGFORM_WHITELIST | quote }}
        image: {{ required "Missing value USER_API_IMAGE" .Values.USER_API_IMAGE }}
        imagePullPolicy: Always
        name: user-api
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value FDK_USER_API_MEMORY" .Values.FDK_USER_API_MEMORY | quote }}
      restartPolicy: Always
status: {}
{{ else }} {{ end }}
