{{ if (.Values.USER_API_IMAGE) and .Values.USER_API_IMAGE "true" }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: user-api
  name: user-api
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: user-api
status:
  loadBalancer: {}
{{ else }} {{ end }}